### ISSUE TITLE
How to connect to device?

### ISSUE THREAD

**Issue by Jalle19** [lemanjo/ecowatti#1]
Interesting project, I've tried getting data out of my Ecowatti but haven't found any physical ports on the main board that would support getting data out. Where exactly do you hook your serial device up to, and what type of serial device do you use?

**Comment by lemanjo** [comment]
I assume you can read Finnish 😁

See the [thread](https://lampopumput.info/foorumi/threads/j%C3%A4spi-ecowatti-homeassistant-tuki.35121/) with discussion related to these questions.
